### ISSUE TITLE
Getting "BAD_REQUEST_ERROR"

### ISSUE THREAD

**Issue by nareshphp1** [razorpay/razorpay-magento#112]
Hi, 
I am getting error "There was an error capturing the transaction. BAD_REQUEST_ERROR: The requested URL was not found on the server."  on checkout page when I select payment method Razorpay while placing order in magento site/store.

![checkout life - google chrome 2018-05-01 12 09 39](https://user-images.githubusercontent.com/14833512/39464295-1175e89c-4d3a-11e8-9b49-2bfa77e86af5.png)

**Comment by Mayur-Wadpalliwar** [comment]
This was handled over email.

Issue: port was not opened for `https://api.razorpay.com` on `443`

**Comment by ashksin121** [comment]
> This was handled over email.
> 
> Issue: port was not opened for `https://api.razorpay.com` on `443`

Can you please elaborate on the matter as I'm new to the feature

**Comment by apoorvnag** [comment]
I am facing the same issue. What should I do to fix this?

API Endpoint: https://api.razorpay.com/v1/payouts

The response is always shown as BAD_REQUEST_ERROR{ "error": { "code": "BAD_REQUEST_ERROR", "description": "The requested URL was not found on the server.", "source": null, "step": null, "reason": null, "metadata": {} }}

**Comment by satya-kalluri** [comment]
Was this resolved? This is the last step of our app-development and I found a major road-block.

**Comment by ramth05** [comment]
> Was this resolved? This is the last step of our app-development and I found a major road-block.

@satya-kalluri , can you please let us know  which version of Magento and plugin you are using.

**Comment by satya-kalluri** [comment]
> > Was this resolved? This is the last step of our app-development and I found a major road-block.
> 
> @satya-kalluri , can you please let us know which version of Magento and plugin you are using.

Apologies. I was using NPM module,  not magento. In haste,  I've posted in the wrong group. 
Correct concern posted at https://github.com/razorpay/razorpay-node/issues/148

**Comment by satya-kalluri** [comment]
> > > Was this resolved? This is the last step of our app-development and I found a major road-block.
> > 
> > 
> > @satya-kalluri , can you please let us know which version of Magento and plugin you are using.
> 
> Apologies. I was using NPM module, not magento. In haste, I've posted in the wrong group.
> Correct concern posted at [razorpay/razorpay-node#148](https://github.com/razorpay/razorpay-node/issues/148)

I have got it resolved by registering my account at x.razorpay.com : https://github.com/razorpay/razorpay-node/issues/148#issuecomment-721222779

**Comment by karthick-d** [comment]
{"error":{"code":"BAD_REQUEST_ERROR","description":"No appropriate payment method found.","source":"customer","step":"payment_authentication","reason":"payment_error","metadata":{}}}

**Comment by GODZ-k** [comment]
i am still facing the same error
{
[1]   statusCode: 400,
[1]   error: {
[1]     code: 'BAD_REQUEST_ERROR',
[1]     description: 'The requested URL was not found on the server.',
[1]     source: 'NA',
[1]     step: 'NA',
[1]     reason: 'NA',
[1]     metadata: {}
[1]   }
[1] }

how can i resolve this because this is the major issue and gonna block the development .
