### ISSUE TITLE
NOTE support magento 2.3,

### ISSUE THREAD

**Issue by shajuss** [razorpay/razorpay-magento#125]
please update new version support Magento 2.3

**Comment by shajuss** [comment]
after install  admin panel error display

**Comment by iambaljitdhanoa** [comment]
We have fixed razorpay issue in magento 2.3

**Comment by sgaykhe** [comment]
Hi Seher,
I am still facing problems installing it on my magento 2.3 community version.
my php version is 7.1.27
Can u please help me with the same.

Thanks

**Comment by sgaykhe** [comment]
Problem 1
    - The requested package magento/framework could not be found in any version, there may be a typo in the package name.

**Comment by sgaykhe** [comment]
{
    "name": "rzp/magento",
    "description": "Razorpay Magento 2.3 plugin for accepting payments.",
    "require": {
        "php": "~5.5.0|~5.6.0|~7.1",
        "magento/framework": "~100.0||~101.0||~102.0",
        "razorpay/razorpay": "2.*"
    },

**Comment by sgaykhe** [comment]
hi Seher,
Can u please help

**Comment by sgaykhe** [comment]
> Hi Seher,
> I am still facing problems installing it on my magento 2.3 community version.
> my php version is 7.1.27
> Can u please help me with the same.
> 
> Thanks

can u please help

**Comment by iambaljitdhanoa** [comment]
Hello

Please let me know how can help you ?

<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=9baa77ad-dcd9-4b6f-b2c5-99d5486baf9e>
I’m
protected online with Avast Free Antivirus. Get it here — it’s free forever.
<https://www.avast.com/en-in/recommend?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=default3&tag=9baa77ad-dcd9-4b6f-b2c5-99d5486baf9e>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by sgaykhe** [comment]
this is the error coming.
- The requested package magento/framework could not be found in any version, there may be a typo in the package name.

**Comment by harman28** [comment]
Closing this as support for Magento 2.3 was added in [v.2.6.1](https://github.com/razorpay/razorpay-magento/releases/tag/2.6.1).

@sgaykhe Could you open a new issue for the problem you're facing, and add more details for the same? Specifically an error trace would be useful.
